%global common_desc \
This package contains a Sphinx extension for BibTeX style citations.\
This extension allows BibTeX citations to be inserted into documentation\
generated by Sphinx, via a bibliography directive, and a cite role,\
which work similarly to LaTeX thebibliography environment and cite command.

Name:           python-sphinxcontrib-bibtex
Version:        2.4.2
Release:        1
Summary:        Sphinx extension for BibTeX style citations
License:        BSD
URL:            https://github.com/mcmtroffaes/sphinxcontrib-bibtex
Source0:        https://github.com/mcmtroffaes/sphinxcontrib-bibtex/archive/%{version}/sphinxcontrib-bibtex-%{version}.tar.gz
BuildArch:      noarch

BuildRequires:  python3-coverage python3-devel python3-latexcodec python3-nose2
BuildRequires:  python3-pybtex python3-pybtex-docutils python3-setuptools python3-six
BuildRequires:  python3-sphinx python3-sphinx-testing python3-pytest python3-sphinxcontrib-bibtex



%description
%common_desc

%package -n python3-sphinxcontrib-bibtex
Summary:        Sphinx extension for BibTeX style citations
Requires:       python3-latexcodec python3-pybtex python3-pybtex-docutils python3-six
Provides:       bundled(jquery)
Provides:       bundled(js-underscore)
%{?python_provide:%python_provide python3-sphinxcontrib-bibtex}

%description -n python3-sphinxcontrib-bibtex
%common_desc

%package help
Summary:       Provides help and documentation for python-sphinxcontrib-bibtex
Obsoletes:     python-sphinxcontrib-bibtex-doc < %{version}-%{release}
Provides:      python-sphinxcontrib-bibtex-doc = %{version}-%{release}

%description help
Help and documentation for python-sphinxcontrib-bibtex.

%prep
%setup -q -c

rm -rf sphinxcontrib-bibtex-%{version}/test/{test_issue1.py,issue1}

%build
cd sphinxcontrib-bibtex-2.4.2
%py3_build

PYTHONPATH=$PWD sphinx-build-%{python3_version} doc html
rm -rf html/{.buildinfo,.doctrees}

%install
cd sphinxcontrib-bibtex-2.4.2
%py3_install

%check
cd sphinxcontrib-bibtex-2.4.2
PYTHONPATH=$PWD nose2-%{python3_version} -v

%files -n python3-sphinxcontrib-bibtex
%license sphinxcontrib-bibtex-%{version}/LICENSE.rst
%{python3_sitelib}/sphinxcontrib/
%{python3_sitelib}/sphinxcontrib_bibtex*

%files help
%doc sphinxcontrib-bibtex-%{version}/html/*

%changelog
* Tue May 31 2022 lvxiaoqian <xiaoqian@nj.iscas.ac.cn> - 2.4.2-1
- update to 2.4.2

* Tue Mar 10 2020 tianhang <1748215448@qq.com> - 0.4.0-4
- Package init
